### ISSUE TITLE
Installer step 6 failed (Uncaught PHP Exception PDOException)

### ISSUE THREAD

**Issue by afbora** [forkcms/forkcms#1524] opened 2016-06-15 09:23 UTC
### Uncaught PHP Exception PDOException

Fork CMS 4.0.2
PHP 5.6.15
MySQL 5.7.9
Apache 2.4.17
On WampServer

> request.CRITICAL: Uncaught PHP Exception PDOException: "SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes" at D:\wamp\www\cms\fork\vendor\spoon\library\spoon\database\database.php line 288 {"exception":"[object] (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes at D:\\wamp\\www\\cms\\fork\\vendor\\spoon\\library\\spoon\\database\\database.php:288)"} []

**Comment by jeroendesloovere** [comment] 2016-06-15 09:24
Hi @afbora did you try to install custom modules when installing Fork CMS?

**Comment by WouterSioen** [comment] 2016-06-15 09:25
probably related to the utf8mb4 changes (poke @jessedobbelaere )

**Comment by afbora** [comment] 2016-06-15 09:27
@jeroendesloovere I selected all modules :smile:

**Comment by afbora** [comment] 2016-06-15 09:31
I tried to new install with only core modules and same error like following and with `Uncaught PHP Exception PDOException` in logs

> Oops! An Error Occurred
> 
> The server returned a "500 Internal Server Error".
> 
> Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by WouterSioen** [comment] 2016-06-15 09:31
Hmm, I've just tested this and couldn't reproduce the issue. (also selected all modules)

**Comment by afbora** [comment] 2016-06-15 09:33
And tried `default-storage-engine=InnoDB` mysql option but nothing changed.

**Comment by WouterSioen** [comment] 2016-06-15 09:34
all create table statements include the storage engine, so that couldn't be the problem. I'll check if I can test this with the same mysql version.

Can you find more about the error? (like a stack trace?) This could help us find out which module caused the issue.

**Comment by WouterSioen** [comment] 2016-06-15 09:41
@afbora you can toggle debug mode by putting `$env = 'dev';$debug = true;` under this line: https://github.com/forkcms/forkcms/blob/master/index.php#L29 (or by setting the right environment variables)

Can you install again with this change? This should give you a nice stack trace of the error. (probably even containing the query causing the issue.

**Comment by jeroendesloovere** [comment] 2016-06-15 09:41
@afbora Is your database using the required charset "utf8mb4"?

**Comment by WouterSioen** [comment] 2016-06-15 09:42
@jeroendesloovere all our queries set the right charset, so this shouldn't be a problem at all.

**Comment by jeroendesloovere** [comment] 2016-06-15 09:43
@WouterSioen ok, didn't know this. @afbora, you can ignore my question then.

**Comment by afbora** [comment] 2016-06-15 09:45
@jeroendesloovere utf8_unicode_ci

@WouterSioen I couldnt find stack traces. Can i enable from ForkCMS configuration?

**Comment by WouterSioen** [comment] 2016-06-15 09:45
adding `$env = 'dev';$debug = true;` under this line: https://github.com/forkcms/forkcms/blob/master/index.php#L29 or setting the right environment variables should enable stack traces.

**Comment by jeroendesloovere** [comment] 2016-06-15 09:48
or the same can be achieved by adding the following into your `.htaccess`.
```bash
# Set debug mode if the host starts or ends in .dev or in .xip.io
<IfModule mod_setenvif.c>
    SetEnvIf Host (localhost|\.xip\.io:8888|\.dev) FORK_DEBUG=1
    SetEnvIf Host (localhost|\.xip\.io:8888|\.dev) FORK_ENV=dev
</IfModule>
```

**Comment by afbora** [comment] 2016-06-15 09:49
![bug](https://cloud.githubusercontent.com/assets/3393422/16075427/99ac18d0-32f7-11e6-8f13-a6e3c72cbd76.png)

**Comment by WouterSioen** [comment] 2016-06-15 09:53
Can you try the install again after changing this?

src/Backend/Core/Installer/Data/install.sql line 14

from

```
KEY `idx_url` (`url`)
```

to

```
KEY `idx_url` (`url`(249))
```

**Comment by afbora** [comment] 2016-06-15 09:56
@WouterSioen Fork CMS is installed! :smile: :clap:

**Comment by WouterSioen** [comment] 2016-06-15 10:00
Ok, I'll do a pull request, thanks for testing this so fast!

**Comment by afbora** [comment] 2016-06-15 10:02
Thanks for amazing assist!

**Comment by afbora** [comment] 2016-06-15 10:05
New issue about analytics `only dashboard`. I have not setup analytics options but this is normal?

> Oops! An Error Occurred
> 
> The server returned a "500 Internal Server Error".
> 
> Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

### Logs

> [2016-06-15 13:03:18] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "analytics.connector"." at D:\wamp\www\cms\fork\vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Container.php line 303 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"analytics.connector\". at D:\\wamp\\www\\cms\\fork\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\DependencyInjection\\Container.php:303)"} []

**Comment by WouterSioen** [comment] 2016-06-15 10:06
your cache is probably corrupt because of the failed installs. Try removing the content of the folders in `app/cache`
The folders will probably be `app/cache/dev` and `app/cache/prod`

**Comment by afbora** [comment] 2016-06-15 10:08
Ohh my mistake, sorry! Fixed.

**Comment by WouterSioen** [comment] 2016-06-15 11:29
bugfix merged in master, thx!

**Closed** 2016-06-15 11:29 UTC
Labels: Bug, Installer

**Comment by jeroendesloovere** [comment] 2016-06-15 12:30
@afbora If you have more questions, you can find every fork developer in the [ForkCMS channel on Slack](https://fork-cms.herokuapp.com).

**Comment by afbora** [comment] 2016-06-15 12:32
@jeroendesloovere I'll be there, thanks ;))

**Comment by jeroendesloovere** [comment] 2016-06-15 12:33
W're all happy to help.
