### ISSUE TITLE
Fork 4.0.0 new UI issues

### ISSUE THREAD

**Issue by freshface** [forkcms/forkcms#1488] opened 2016-06-02 14:13 UTC
- [x] Single element in panel http://jmp.sh/aJTJXnp
- [x] datagrid Blog/ Comments , column to wide http://jmp.sh/mRV4ehE
- [x] Formbuilder field icons http://jmp.sh/oxaQcef
- [x] Installer: previous button is underlined http://jmp.sh/NKJfgZ0
- [x] Installer: required asterisk should not be an icon http://jmp.sh/O3VTmZb
- [x] Installer: password strength http://jmp.sh/5UbTMoK update, should be same as http://jmp.sh/CrtSkte
- [x] Different use of save icons: http://jmp.sh/OHEnIq2 and http://jmp.sh/PyD8awU
- [x] Label when changing template: http://jmp.sh/ErDS0jP
- [x] Use of spaces http://jmp.sh/czAXSzv
- [x] thead hover state http://jmp.sh/QikVpyz
- [x] Should be a link http://jmp.sh/Ucw8KtN
- [x] Translations bug, no results without value http://jmp.sh/nuJRYb7
- [x] tables without a hover state http://jmp.sh/GJF4Q4w
- [x] Pages: template choice http://jmp.sh/cVbQQD4
- [x] Buttons http://jmp.sh/6RpkEto
- [x] Themes add block http://jmp.sh/6RpkEto
- [x] Themes delete block icon not sharp http://jmp.sh/vBosoxw
- [x] Missing translation http://jmp.sh/bqk1faQ
- [x] After installing a module via the cms the system logs you out.

**Comment by jessedobbelaere** [comment] 2016-06-02 14:18
In addition: 
* Installer: remove large space between label and field http://jmp.sh/O3VTmZb
* Installer: padding bottom under the buttons is small, while padding left&right of the form is larger. Make padding consistent
* Installer: Could use more blue instead of gray to make it less boring. Maybe a blue tint in the background color or somewhere, or put a logo of fork somewhere

**Comment by freshface** [comment] 2016-06-02 14:19
- Forgot password is not working when trying to login.

**Comment by carakas** [comment] 2016-06-02 14:22
what is wrong with using an icon as asterisk ?

**Comment by freshface** [comment] 2016-06-02 14:23
@carakas It is not consistent with the asterisk in the backend http://jmp.sh/LiUc8yo + it looks to big

**Comment by carakas** [comment] 2016-08-09 07:02
any update on this ?

**Comment by carakas** [comment] 2016-08-21 13:15
I've turned the list into a checklist, I'm doing some things now and checking them off as I go along

**Comment by carakas** [comment] 2016-08-21 13:18
@jessedobbelaere about the space between the label and the field, do you still have this?
I see a message there, so it might be that you are missing a translation
<img width="452" alt="screen shot 2016-08-21 at 15 17 14" src="https://cloud.githubusercontent.com/assets/3634654/17837395/7ec1b4fe-67b2-11e6-97d8-0d5df41eddba.png">

**Comment by carakas** [comment] 2016-08-21 13:50
@freshface  Translations bug, no results without value http://jmp.sh/nuJRYb7  was not a bug, the module just doesn't have module specific translations.

For other modules it works, or maybe it got fixed by now :)

**Comment by jessedobbelaere** [comment] 2016-08-21 16:20
@carakas Yes seems like the label is there now. Asterix look fine too 👍 
About the button paddings, nvm that

**Comment by carakas** [comment] 2016-08-31 14:11
Alert/ Message padding won't be fixed

**Closed** 2016-09-02 11:51 UTC
Labels: Enhancement, Installer
