### ISSUE TITLE
User Template images not removed after delete

### ISSUE THREAD

**Issue by vanMeerdervoort** [forkcms/forkcms#2631] opened 2018-09-04 06:56 UTC
## Type

- Non critical bug

## Problem description

When deleting a UserTemplate block from a page, images in the template do not get removed. This results in orphaned images in the Frontend Files folder.

## Steps to reproduce

Add a UserTemplate with an image to a page. Save. See the image appear in the Files folder.
Delete the UserTemplate block from the page. See the image still in the Files folder.

## Expected behavior / Proposed solutions

Make sure the deletion of a UserTemplate block also deletes attached images.

**Comment by thibautvincent** [comment] 2018-09-13 19:31
Isn't this one by design?
I'm thinking about using the versioning of a page. If you want to go back to a version where there is a UserTemplate, we also want to show the image that is linked to the UserTemplate.
So if we delete the image, the revision isn't like it should be.

**Comment by carakas** [comment] 2018-09-14 08:54
True, good point, I'll mark this as won't fix

**Closed by carakas** 2018-09-14 08:54 UTC
