### ISSUE TITLE
Single quotes in urlname get escaped in frontend en backend

### ISSUE THREAD

**Issue by bramds** [forkcms/forkcms#1389] opened 2016-02-09 07:59 UTC
Single quotes get escaped in backend and frontend navigation. 
Ex:
Foto's becomes foto\'s in backend navigation and in frontend navigation widget.  The  link itself is correct and works ( /foto-s )
It would actually also make more sense to get /fotos instead of /foto-s.

![fork396-2](https://cloud.githubusercontent.com/assets/2137063/12910492/6eac9f6a-cf0b-11e5-879b-f8f285210563.JPG)

![fork396-1](https://cloud.githubusercontent.com/assets/2137063/12910494/73ff2488-cf0b-11e5-93c8-35b5574fc0a3.JPG)

**Comment by WouterSioen** [comment] 2016-02-09 08:04
@jonasdekeukelaere I guess this is due to your escaping of double quotes? Can you take a look at this?

**Comment by jeroendesloovere** [comment] 2016-02-09 09:08
@bramds: Which Fork CMS version are you using?
I think I looked into this a long time ago.
This problem isn't reproducible anymore in [Fork CMS Demo site](http://demo.fork-cms.com).

**Comment by jeroendesloovere** [comment] 2016-02-09 09:09
@bramds: did you do a "copy/past" of "foto's", or did you type it in yourself?

**Comment by jeroendesloovere** [comment] 2016-02-09 09:10
Strange: it can be reproduced in a page (other then home).
![schermafbeelding 2016-02-09 om 10 10 02](https://cloud.githubusercontent.com/assets/588616/12911827/5cc6ded2-cf15-11e5-994c-5401d7ecbe2f.png)

**Comment by jeroendesloovere** [comment] 2016-02-09 09:13
Maby it is related to [BUG: Special characters in Page URL](https://github.com/forkcms/forkcms/issues/1198)

**Comment by jeroendesloovere** [comment] 2016-02-09 09:25
The problem from @bramds is coming from [these rules in src/Backend/Modules/Pages/Engine/CacheBuilder.php](https://github.com/forkcms/forkcms/blob/master/src/Backend/Modules/Pages/Engine/CacheBuilder.php#L172-L173)

**Comment by WouterSioen** [comment] 2016-02-09 09:25
@jeroendesloovere I think it's related to https://github.com/forkcms/forkcms/pull/1314, that's why I poked @jonasdekeukelaere

**Comment by WouterSioen** [comment] 2016-02-09 09:36
not related to @jonasdekeukelaere 's Pull Request, sorry :wink: 

I guess @jeroendesloovere found the source of the bug. :+1:

**Comment by WouterSioen** [comment] 2016-02-09 09:38
It's introduced by @tommyvdv in https://github.com/forkcms/forkcms/commit/325968737dd1793046aa04603725ed429bb7a048

Do you still have an idea what the issue was here? (I don't even know why we need to escape the title)

**Comment by jeroendesloovere** [comment] 2016-02-09 09:48
This was probably to prevent "the cache file" from breaking.
The "cache file", which is now replaced by MatthiasMullie\Scrapbook?

**Comment by WouterSioen** [comment] 2016-02-09 09:52
Ok, this should be tested.

**Comment by jeroendesloovere** [comment] 2016-02-09 09:54
When removing that preg_replace, everything is fixed in backend pages navigation.

**Comment by WouterSioen** [comment] 2016-02-09 09:54
Can you do a PR?

**Comment by jeroendesloovere** [comment] 2016-02-09 09:55
And ```editor_link_list_nl.js``` is also working since we use "double quotes" as you can see here.
![schermafbeelding 2016-02-09 om 10 50 04](https://cloud.githubusercontent.com/assets/588616/12912845/7821e234-cf1b-11e5-9b5c-0fb94365dc03.png)

**Closed** 2016-02-09 10:26 UTC
Labels: Bug, Pages
