### ISSUE TITLE
Latest Fork CMS master - white page after install

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1332] opened 2015-11-25 18:44 UTC
I've just installed the latest Fork CMS from the master branch with success.
But when I try to visit (any page on) the website (even /private) you see a white page.

**Comment by WouterSioen** [comment] 2015-11-25 19:12
Have you checked the logs? (Both application and apache/php logs)

Op woensdag 25 november 2015 heeft Jeroen Desloovere <
notifications@github.com> het volgende geschreven:

**Comment by jessedobbelaere** [comment] 2015-11-25 19:15
I just did a [clean install](http://forktest.jessedobbelae.re/) on my shared hosting and it runs nicely so far. 
But I had to upgrade my php version on my shared hosting a week ago. I was still running php 5.3.3 and composer aborted because php >5.3 had to be used because of flysystem cache etc. If you're using the zip from the website, you probably didn't get the composer warning

**Comment by WouterSioen** [comment] 2015-11-26 16:32
@jeroendesloovere have you checked your php version? And your logs?

**Comment by jeroendesloovere** [comment] 2015-11-27 07:51
Deleted the folder.

**Comment by jeroendesloovere** [comment] 2015-12-03 16:10
Dunno why this happened.

**Comment by WouterSioen** [comment] 2015-12-21 14:34
@jeroendesloovere have you already checked you php version? I'll close this issue without any more info, since I can't reproduce it (on supported php versions)

**Closed** 2015-12-22 09:50 UTC
Labels: Bug, Critical

**Comment by jeroendesloovere** [comment] 2015-12-27 17:50
Hi, I just did a clean install.
Same problem as described.
Checked the logs:
```php
request.CRITICAL: Uncaught PHP Exception Exception: "DateTime::__construct(): Invalid date.timezone value 'UTF', we selected the timezone 'UTC' for now."
```
=> Probably caused by my new mac

**Comment by jeroendesloovere** [comment] 2015-12-27 17:54
Could we add something to prevent this for newbies?
