### ISSUE TITLE
You have requested a non-existent service "analytics.connector". 

### ISSUE THREAD

**Issue by V3nn3tj3** [forkcms/forkcms#1462] opened 2016-05-03 09:53 UTC
I'm having this problem for quite some time now on several fork installs.

```
You have requested a non-existent service "analytics.connector".
500 Internal Server Error - ServiceNotFoundException 
```
This happens when i login or want to create a new group of users, etc.
When debugging i see that the analytics service does not exist.

I also see that buildContainer from Kernel does not get called for some reason. So the service will never be found as it is never created.

Any idea's?

**Comment by WouterSioen** [comment] 2016-05-03 09:55
seems like your cache was build when no database connection was available.

try `rm -rf app/cache/<environment>`, so `rm -rf app/cache/dev` when you're in dev mode

**Comment by V3nn3tj3** [comment] 2016-05-03 09:55
Edit in Kernel.php seems to fix it. But not sure what it all does, so don't know if it is a good idea...  

```
  public function boot()
    {
        if ($this->booted) {
            return;
        }

        parent::boot();

        // define Fork constants
        $this->defineForkConstants();
        self::buildContainer(); <---- This line
    }
```

**Comment by WouterSioen** [comment] 2016-05-03 09:56
building your container in every request would be a really bad thing to do, because it takes a lot of time.

**Comment by V3nn3tj3** [comment] 2016-05-03 09:58
That was what i was thinking. Will have a look if there is a way to detect and rebuild only when necessary... (if not already present)

**Comment by WouterSioen** [comment] 2016-05-03 09:59
The problem is that you've probably ran `remove_cache` on a place where no database connection was available. This way, the cache was built without the analytics services in there.

If you for example use vagrant, it's better to always run cli tools from inside your vagrant box, or remove the container cache after running your scripts.

**Comment by jeroendesloovere** [comment] 2016-05-03 10:00
I discovered that all custom modules (which contain a "service" integration or parameter from the /app/config/parameters.yml file) throw errors:
* When trying to install fork cms
* When deploying using Capistrano

I found a solution, but only for parameters (from /app/config/parameters.yml)
[Example in fork cms module mailmotor CustomCompilerPass.php](https://github.com/mailmotor/fork-cms-module-mailmotor/blob/master/src/Backend/Modules/MailMotor/DependencyInjection/Compiler/CustomCompilerPass.php)

**Comment by WouterSioen** [comment] 2016-06-15 15:08
I'll close this because it's duplicated and not updated for some time

**Closed by WouterSioen** 2016-06-15 15:08 UTC
Labels: Bug
