### ISSUE TITLE
Refactor ModuleInstaller to actually work as an Installer and Uninstaller

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1538] opened 2016-06-21 15:16 UTC
**Problem**

You can't uninstall a module. Which can be a pain in the ass sometimes.

**Solution**

Refactor the "ModuleInstaller", so it can be used to Install or Uninstall a module.

**Comment by WouterSioen** [comment] 2016-06-21 15:17
duplicate of https://github.com/forkcms/forkcms/issues/872

**Closed by WouterSioen** 2016-06-21 15:17 UTC
Labels: Feature
