### ISSUE TITLE
Reduce database queries for /private/nl/extensions/themes page

### ISSUE THREAD

**Issue by jeroendesloovere** [forkcms/forkcms#1483] opened 2016-06-01 12:24 UTC
I've got 4 themes available and the database query counter says **322**
![schermafbeelding 2016-06-01 om 14 22 49](https://cloud.githubusercontent.com/assets/588616/15709334/6d3efdce-2804-11e6-97ca-5b5db812b973.png)

**Comment by WouterSioen** [comment] 2016-08-23 11:42
Thats odd, I have 9 queries with 2 themes (core and triton).

Can you still reproduce this?

**Comment by carakas** [comment] 2016-08-24 22:59
@jeroendesloovere any update on this?

**Comment by jeroendesloovere** [comment] 2016-08-25 08:05
Hi @WouterSioen,
I've just tested this and it still exists.

Steps to reproduce:
* Copy/paste a theme from a customer
* Install it
* **Active that theme**, in my case this increases the database queries from "10" to "116"
![schermafbeelding 2016-08-25 om 10 05 04](https://cloud.githubusercontent.com/assets/588616/17961349/6a9ab7c2-6aab-11e6-9440-7ad03e31a3ee.png)

**Comment by tijsverkoyen** [comment] 2016-08-25 08:23
So this is only happening on activating a theme. Seems like a whole other issue.

**Comment by jeroendesloovere** [comment] 2016-08-25 09:31
When installing a theme, activating it and then reactivating the previous theme.
The queries still remain.

In my example:
It goes from "116" queries to "114" when activating "triton" again.

**Comment by carakas** [comment] 2016-08-25 09:35
I've looked at the code behind it and it has to do with porting the pages from one theme to another. It is not something that can be changed overnight
since it is only on those specific actions I don't think this is a big issue so I'll close it since I don't see a solution for it at the moment

**Closed by carakas** 2016-08-25 09:35 UTC
Labels: Enhancement, Extensions
