### ISSUE TITLE
All functional tests failing in a custom install

### ISSUE THREAD

**Issue by GhaziTriki** [forkcms/forkcms#1215] opened 2015-05-27 19:50 UTC
Hi there,

I have all functional tests failing in a custom install of Fork CMS.

Examples : 

=> CategoryTest::testNonExistingCategoryPostGives404 gives The request was not redirected.
=> Backend\IndexTest::testAuthenticationIndexWorks gives

Failed asserting that 500 matches expected 200.
Expected :200
Actual   :500

I have checked that I have "test_db.sql" in tools folder which is a dump of the production database.

**Comment by WouterSioen** [comment] 2015-06-03 14:36
Do you have more output from the tests? We can't really say what's the cause with this information.

You get an error 500, have you checked the logs (in Symfony and on your server)?

**Comment by jeroendesloovere** [comment] 2015-06-23 07:13
@GhaziTriki Can you inform us with some more details? Or is it OK now?

**Comment by WouterSioen** [comment] 2015-07-08 14:58
We'll close this until we get more info.

**Closed by WouterSioen** 2015-07-08 14:58 UTC
Labels: Bug, Unconfirmed
